stages:
  - dockerize

dockerize:
  stage: dockerize
  image: docker:latest
  only:
    - master
    - merge_requests
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  after_script:
    - docker logout "$CI_REGISTRY"