version: "3.9"

services:
  ghost:
    image: ghost:alpine
    restart: always
    environment:
      NODE_ENV: production
      process: "systemd"
      server__port: "2368"
      server__host: "0.0.0.0"
      url: ${WEB_URL}
      admin__url: ${ADMIN_URL}
      database__client: mysql
      database__connection__host: db
      database__connection__port: 3306
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      privacy__useUpdateCheck: true
      privacy__useGravatar: true
      privacy__useRpcPing: true
      privacy__useStructuredData: true
      mail__transport: "SMTP"
      mail__logger: true
      mail__from: ${MAIL_FROM}
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT}
      mail__options__secureConnection: false
      mail__options__auth__user: ${MAIL_USERNAME}
      mail__options__auth__pass: ${MAIL_PASSWORD}
      adapters__cache__Redis__host: "redis"
      adapters__cache__Redis__port: "6379"
      adapters__cache__Redis__password: ${REDIS_PASSWORD}
      adapters__cache__imageSizes__adapter: "Redis"
      adapters__cache__imageSizes__ttl: "3600"
      adapters__cache__imageSizes__keyPrefix: "image-sizes:"
      adapters__tenor__googleApiKey: ${TENOR_API_KEY}
      paths__contentPath: "/var/lib/ghost/content"
    volumes:
      - ${BASE_VOLUME}/content:/var/lib/ghost/content
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    expose:
      - 2368
    networks:
      - internal
      - nginx
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_GHOST_CPU:-1}
          memory: ${LIMIT_GHOST_RAM:-256M}
        reservations:
          cpus: "0.5"
          memory: 128M
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${BASE_VOLUME}/db:/var/lib/mysql
    expose:
      - 3306
    networks:
      - internal
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_DB_CPU:-1}
          memory: ${LIMIT_DB_RAM:-1G}
        reservations:
          cpus: "0.1"
          memory: 16M
  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - 6379
    networks:
      - internal
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${BASE_VOLUME}/cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      retries: 3
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_REDIS_CPU:-1}
          memory: ${LIMIT_REDIS_RAM:-1G}
        reservations:
          cpus: "0.1"
          memory: 16M

networks:
  internal:
  nginx:
    external: true
